config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'stores#index'

  resources :stores do
  resources :products
  end
  resources :products do
    resources :reviews
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_store
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  def index
    @products = @store.products
  end

  def show
    
  end

  def new
    @product = @store.products.new
  end

  def create
    @product = @store.products.new(product_params)
    if @product.save
      redirect_to store_products_path(@store)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to store_products_path(@store)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to store_products_path(@store)
  end

  private
  def set_store
    @store = Store.find(params[:store_id])
  end
  def set_product
    @product = Product.find(params[:id])
  end
  def product_params
    params.require(:product).permit(:product_name, :product_price)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_product
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  def index
    @reviews = @product.reviews.all
  end

  def show

  end

  def new
    @review = Review.new
  end

  def create
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_reviews_path(@product.id)
    else
      render :new
    end
  end
  def edit
  end

  def update
    @review = Review.find(params[:id])
      
      if @review.update(review_params)
        redirect_to product_reviews_path(@product.id)
      else
        render :edit
      end
    end

    def destroy
      @review.destroy
      redirect_to product_reviews_path(@product.id)
    end

  private
  def set_review
    @review = Review.find(params[:id])
  end

  def set_product
    @product = Product.find(params[:product_id])
  end

  def review_params
    params.require(:review).permit(:name, :subject, :message)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :update, :edit, :destroy]
  # before_action :set_product, only: [:show]
  def index
    @stores = Store.all
  end

  def show

  end

  def new
    @store = Store.new
  end

def create
  @store = Store.new(store_params)

  if @store.save
    redirect_to stores_path
  else
    render :new
  end
end

  def edit
  end

  def update
    if @store.update(store_params)
      redirect_to stores_path
    else
      render :edit
    end
  end

  def destroy
    @store.destroy
    redirect_to stores_path
  end

  private
    def set_store
      @store = Store.find(params[:id])
    end

    def store_params
      params.require(:store).permit(:store_name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/_navbar.html.erb
<div class="ui tabular menu">
  <div class='item'>
    <%= link_to '<i class="home icon"></i>'.html_safe, root_path%>
  </div>
 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChainStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class='ui container'>
    <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit <%= @product.product_name %></h1>


<div class='ui form'>
<%= form_for [@store, @product] do |f| %>

  <%= f.label :product_name %>
  <%= f.text_field :product_name, required: true, autofocus: true %>
  <%= f.label :product_price %>
  <%= f.number_field :product_price, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>
</div>

app/views/products/index.html.erb
<h1 class='ui header'>Products For <%=  @store.store_name %></h1>

<table class = 'ui table'>
<thead>
<tr>
  <th>Product Name</th>
  <th>Product Price<th>
  <th>Product page<th>
  <th>Edit<th>
  <th>Destroy<th>
  </tr>
</thead>
<tbody>
<% @store.products.each do |product|%>
<tr>
  <td><%= product.product_name%></td>
  <td><div class="ui tag labels">
            <a class="ui label">
              $<%=product.product_price %>
            </a></td>
  <td><%= link_to "See Reviews", product_reviews_path(product.id)%></td>
  <td><%= link_to "Edit Product", edit_store_product_path(@store, product.id)%></td>
  <td><%= link_to "Product Info", store_product_path(@store, product) %></td>
</tr>
<% end %>
</tbody>
</table>

<%= link_to "Add a Product", new_store_product_path(@store)%>

app/views/products/new.html.erb
<h1>Products#new</h1>
<h1>Add a Product</h1>

<div class = 'ui form'>
  <%= form_for [@store, @product] do |f|%>
    <div class='field'>
      <%= f.label :product_name%>
      <%= f.text_field :product_name%>
    </div>  
    <div class='field'>
      <%= f.label :product_price%>
      <%= f.number_field :product_price%>
    </div>  
  
     <%= f.submit %>
  <% end%>
<div>

app/views/products/show.html.erb
<h1 class='ui header'>Product Show</h1>


<div class="ui link cards">
  <div class="card">
    <div class="content">
      <div class="header">
        <%= @product.product_name %>
      </div>
      <br>
      <div class="meta">
         <td><div class="ui tag labels">
            <a class="ui label">
              $<%=@product.product_price %>
            </a></td>
      </div>
      <br>
    <div class="extra content">
      <div class="ui two buttons">
        <div class="ui basic green button"><%= link_to 'Edit Item', edit_store_product_path(@store) %></div>
        <div class="ui basic red button"><%= link_to 'Delete', [@store, @product], method: :delete %></div>
      </div>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>
<div class = 'ui form'>
<%= form_for [@product, @review] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, placeholder: 'Leave Blank To Remain Anonymous'  %>
  <br />
  <%= f.label :subject %>
  <%= f.text_field :subject %>
  <br />
  <%= f.label :message %>
  <%= f.text_area :message, placeholder: 'Write your review' %>
  <br />
  <%= f.submit %>
<% end %>
</div>

app/views/reviews/index.html.erb
<br>
<br>
<h1 class='ui header'>Reviews form: <%= @product.product_name %></h1>
  <div class="ui tag labels">
            <a class="ui label">
              $<%=@product.product_price %>
            </a></<div>
<hr>
<button class="ui primary button">
  <a><%= link_to "Write a Review", new_product_review_path %></a>
</button>

<button class="ui secondary button">
  <a><%= link_to "Back", product_reviews_path(@product.id)%></a>
</button>

<hr>
<div class="ui card">
<% @product.reviews.each do |review| %>
   
  <div class="content">
  <div class="header">Name: <%= review.name %></div>
  <div>Subject: <%= review.subject %></div>
  <div>Message: <%= review.message %></div>
   <div class="extra content">
    <span class="left floated like">
      <i class="like icon"></i>
      Like
    </span>
    <span class="right floated star">
      <i class="star icon"></i>
      Favorite
    </span>
    <br>
  <div><%= link_to "Edit", edit_product_review_path(@product, review)%>
  
  </div>
<% end %>
</div>
</div>

app/views/reviews/new.html.erb
<h1>Add A review</h1>
<div class = 'ui form'>
<%= form_for [@product, @review] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, placeholder: 'Leave Blank To Remain Anonymous'  %>
  <br />
  <%= f.label :subject %>
  <%= f.text_field :subject %>
  <br />
  <%= f.label :message %>
  <%= f.text_area :message, placeholder: 'Write your review' %>
  <br />
  <%= f.submit %>
<% end %>
</div>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<h1><%= @store.store_name %> - <%= @product.product_name %></h1>
<p><%= @product.product_price %></p>
<h2>Comments</h2>

<% @product.reviews.each do |review| %>
  <%= render 'reviews/review', { review: review } %>
<% end %>

<hr />
<%= link_to 'Add Comment', new_topic_comment_path(@topic) %>
<%= link_to 'Edit Topic', edit_sub_topic_path([@sub, @topic]) %>
<%= link_to 'Delete Topic', [@sub, @topic], method: :delete %>
<%= link_to 'Back To Topics', sub_topics_path(@sub) %>

app/views/stores/edit.html.erb
<h1>Edit <%= @store.store_name%></h1>
<p>Find me in app/views/stores/edit.html.erb</p>

<div class='ui form'>
<%= form_for @store do |f| %>

  <%= f.label :store_name %>
  <%= f.text_field :store_name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>
</div>

app/views/stores/index.html.erb
<h1>Stores</h1>

<table class = 'ui table'>
<thead>
<th>Store Name</th>
<th>View Store</th>
<th>View Products</th>
</thead>
<tbody>
<% @stores.each do |store|%>
<tr>
    <td><%= store.store_name %></td>
    <td><%= link_to "View Store", store_path(store) %></td>
    <td><%= link_to 'View Store Items', store_products_path(store.id) %></td>
</tr>
<% end %>
</tbody>
</table>

<button class="ui primary button">
  <a><%= link_to "Create a Store", new_store_path%></a>
</button>

app/views/stores/new.html.erb
<h1>Create A Store</h1>

<div class = 'ui form'>
  <%= form_for @store do |f| %>
    <div class='field'>
      <%= f.label :store_name%>
      <%= f.text_field :store_name%>
    </div>  
  
     <button class="ui button"> <%= f.submit %></button>
  <% end%>
</div>

app/views/stores/show.html.erb
<h1>Show page for: <%=  @store.store_name %></h1>

<hr />
<p>What would you like to do?</p>
<%= link_to 'View products', store_products_path(@store) %>
<br />
<%= link_to 'Edit Store', edit_store_path(@store) %>
<br />
<%= link_to 'Delete Store', @store, method: :delete %>